name: capsule
description: A package to facilitate multiple Dart main methods on the same page.
version: 0.1.0
homepage: https://github.com/glesica/capsule.dart
author: George Lesica <george@lesica.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  js: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
